spring:
  datasource:
    url: jdbc:mysql://u1uhjgldadgy5xvt:7hj9Pcm1lxg2Bl9fhDxr@bdmax4es5qlcjobbwkvx-mysql.services.clever-cloud.com:3306/bdmax4es5qlcjobbwkvx
    username: u1uhjgldadgy5xvt
    password: 7hj9Pcm1lxg2Bl9fhDxr
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
server:
  port: 8080
  

